apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: adsb-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://your.git.repo/with/k8s.git
    targetRevision: main
    path: k8s/adsb
  destination:
    server: https://kubernetes.default.svc
    namespace: adsb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
