apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb2-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: longhorn-db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb2-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn-bulk
