apiVersion: v1
kind: Secret
metadata:
  name: influxdb-auth
  namespace: adsb
type: Opaque
stringData:
  INFLUXDB_USER: ultrafeeder
  INFLUXDB_PASSWORD: "super-secret-password"
  INFLUXDB_ADMIN_TOKEN: "super-secret-admin-token"