apiVersion: v1
kind: Service
metadata:
  name: ultrafeeder
  labels:
    app: ultrafeeder
spec:
  selector:
    app: ultrafeeder
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: metrics-telegraf
      port: 9273
      targetPort: metrics-telegraf
    - name: metrics-readsb
      port: 9274
      targetPort: metrics-readsb
